<?php

/**
 * Return a list of all the counties
 */

function moroccocommunes_listcounties() {
  $countryIso = 'MA';
  $counties = array(
    'AGADIR IDA OU TANAN' => array(
      'AGADIR (M)',
      'AMSKROUD',
      'AOURIR',
      'AQESRI',
      'AZIAR',
      'DRARGUA',
      'IDMINE',
      'IMOUZZER',
      'IMSOUANE',
      'TADRART',
      'TAGHAZOUT',
      'TAMRI',
      'TIQQI',
    ),
    'AL HAOUZ' => array(
      'AIT OURIR (M)',
      'ABADOU',
      'AGHBAL',
      'AIT AADEL',
      'AIT FASKA',
      'AIT HKIM AIT YZID',
      'AIT SIDI DAOUD',
      'AMGHRAS',
      'AMIZMIZ',
      'ANOUGAL',
      'ASNI',
      'AZGOUR',
      'DAR JAMAA',
      'GHMATE',
      'IGHIL',
      'IGUERFEROUANE',
      'IJOUKAK',
      'IMGDAL',
      'LALLA TAKARKOUST',
      'MOULAY BRAHIM',
      'OUAZGUITA',
      'OUIRGANE',
      'OUKAIMDEN',
      'OULAD MTAA',
      'OURIKA',
      'SIDI ABDALLAH GHIAT',
      'SIDI BADHAJ',
      'STI FADMA',
      'TAHANNAOUT',
      "TALAT N'YAAQOUB",
      'TAMAGUERT',
      'TAMAZOUZTE',
      'TAMESLOHTE',
      'TAZART',
      'TIDILI MESFIOUA',
      'TIGHEDOUINE',
      'TIZGUINE',
      'TOUAMA',
      'ZERKTEN',
    ),
    'AL HOCEIMA' => array(
      'AL HOCEIMA (M)',
      'BNI BOUAYACH (M)',
      'IMZOUREN',
      'TARGUIST (M)',
      'ABDELGHAYA SOUAHEL',
      'AIT KAMRA',
      'AIT YOUSSEF OU ALI',
      'ARBAA TAOURIRT',
      'BNI ABDALLAH',
      'BNI AHMED IMOUKZAN',
      'BNI AMMART',
      'BNI BCHIR',
      'BNI BOUCHIBET',
      'BNI BOUFRAH',
      'BNI BOUNSAR',
      'BNI GMIL',
      'BNI GMIL MAKSOULINE',
      'BNI HADIFA',
      'CHAKRANE',
      'IMRABTEN',
      'ISSAGUEN',
      'IZEMMOUREN',
      'KETAMA',
      'LOUTA',
      'MOULAY AHMED CHERIF',
      'NEKKOUR',
      'ROUADI',
      'SENADA',
      'SIDI BOUTMIM',
      'SIDI BOUZINEB',
      'TAGHZOUT',
      'TAMSAOUT',
      'TIFAROUINE',
      'ZAOUIAT SIDI ABDELKADER',
      'ZARKT',
    ),
    'AOUSSERD' => array(
      'LAGOUIRA',
      'AGHOUINITE',
      'AOUSSERD',
      'BIR GANDOUZ',
      'TICHLA',
      'ZOUG',
    ),
    'ASSA ZAG' => array(
      'ASSA (M)',
      'ZAG (M)',
      'AL MAHBASS',
      'AOUINT LAHNA',
      'AOUINT YGHOMANE',
      'LABOUIRAT',
      'TOUIZGUI',
    ),
    'AZILAL' => array(
      'AZILAL (M)',
      'DEMNATE (M)',
      'AFOURAR',
      "AGOUDI N'LKHAIR",
      'AIT ABBAS',
      'AIT BLAL',
      'AIT BOU OULLI',
      'AIT MAJDEN',
      'AIT MAZIGH',
      "AIT M'HAMED",
      'AIT OUAARDA',
      'AIT OUMDIS',
      'AIT OUQABLI',
      'AIT TAGUELLA',
      'AIT TAMLIL',
      'ANERGUI',
      'ANZOU',
      'BIN EL OUIDANE',
      'BNI AYAT',
      'BNI HASSANE',
      'BZOU',
      'FOUM JEMAA',
      'IMLIL',
      'ISSEKSI',
      'MOULAY AISSA BEN DRISS',
      'OUAOUIZEGHT',
      'OUAOULA',
      'RFALA',
      'SIDI BOULKHALF',
      'SIDI YACOUB',
      'TABANT',
      'TABAROUCHT',
      'TABIA',
      'TAGLEFT',
      'TAMDA NOUMERCID',
      'TANANT',
      'TAOUNZA',
      'TIDILI FETOUAKA',
      "TIFFERT N'AIT HAMZA",
      'TIFNI',
      'TILOUGGUITE',
      'TIMOULILT',
      'TISQI',
      'ZAOUIAT AHANSAL',
    ),
    'BENI MELLAL' => array(
      'BENI MELLAL (M)',
      'EL KSIBA (M)',
      'KASBA TADLA (M)',
      'ZAOUIAT CHEIKH (M)',
      'AGHBALA',
      'AIT OUM EL BEKHT',
      'BOUTFERDA',
      'DIR EL KSIBA',
      'FOUM EL ANCEUR',
      'FOUM OUDI',
      'GUETTAYA',
      'NAOUR',
      'OULAD GNAOU',
      "OULAD M'BAREK",
      "OULAD SAID L'OUED",
      'OULAD YAICH',
      'OULAD YOUSSEF',
      'SEMGUET',
      'SIDI JABER',
      'TAGHZIRT',
      'TANOUGHA',
      "TIZI N'ISLY",
    ),
    'BENSLIMANE' => array(
     'BENSLIMANE (M)',
      'BOUZNIKA (M)',
      'AHLAF',
      'AIN TIZGHA',
      'BIR ENNASR',
      'CHERRAT',
      'EL MANSOURIA',
      'FDALATE',
      'MELLILA',
      'MOUALINE EL GHABA',
      'MOUALINE EL OUED',
      'OULAD ALI TOUALAA',
      'OULAD YAHYA LOUTA',
      'RDADNA OULAD MALEK',
      'SIDI BETTACHE',
      'ZIAIDA',
    ),
    'BERCHID' => array(
      'BERRECHID (M)',
      'EL GARA (M)',
      'OULAD ABBOU (M)',
      'DEROUA',
      'BEN MAACHOU',
      'FOQRA OULAD AAMEUR',
      'JAQMA',
      'KASBAT BEN MCHICH',
      'LAGHNIMYINE',
      'LAHSASNA',
      'LAMBARKIYINE',
      'OULED CEBBAH',
      'OULED ZIDANE',
      'RIAH',
      "SAHEL OULAD H'RIZ",
      'SIDI ABDELKHALEQ',
      'SIDI EL MEKKI',
      'SIDI RAHAL CHATAI',
      'HAD SOUALEM',
      'ZAOUIAT SIDI BEN HAMDOUN',
      'SWALAM TRIFIYA',
      'OULED ZIYAN',
    ),
    'BERKANE' => array(
      'AHFIR (M)',
      'AIN ERREGGADA (M)',
      'AKLIM (M)',
      'BERKANE (M)',
      'SAIDIA (M)',
      'SIDI SLIMANE ECHCHARAA',
      'AGHBAL',
      'BOUGHRIBA',
      'CHOUIHIA',
      'FEZOUANE',
      'LAATAMNA',
      'MADAGH',
      'RISLANE',
      'SIDI BOUHRIA',
      'TAFOUGHALT',
      'ZEGZEL',
    ),
    'BOUJDOUR' => array(
      'BOUJDOUR (M)',
      'GUELTAT ZEMMOUR',
      'JRAIFIA',
      'LAMSSID',
    ),
    'BOULEMANE' => array(
      'BOULMANE (M)',
      'IMOUZZER KANDAR (M)',
      'MISSOUR (M)',
      'OUTAT EL HAJ (M)',
      'AIT BAZZA',
      'AIT EL MANE',
      'ALMIS MARMOUCHA',
      'EL MERS',
      'EL ORJANE',
      'ENJIL',
      'ERMILA',
      'FRITISSA',
      'GUIGOU',
      'KSABI-MOULOUYA',
      'OUIZEGHT',
      'OULAD YOUSSEF',
      'SERGHINA',
      'SIDI BOUTAYEB',
      "SKOURA M'DAZ",
      'TALZEMT',
      'TISSAF',
    ),
    'CASABLANCA' => array(
      'CASABLANCA',
      'AîN-CHOCK (AR)',
      'AîN-SEBAâ (AR)',
      'ANFA (AR)',
      'AL-FIDA (AR)',
      'ASSOUKHOUR ASSAWDA (AR)',
      "BEN M'SICK (AR)",
      'EL MAARIF (AR)',
      'HAY-HASSANI (AR)',
      'HAY MOHAMMADI (AR)',
      'MERS-SULTAN (AR)',
      'MOULAY RACHID (AR)',
      'SBATA (AR)',
      'SIDI BELYOUT (AR)',
      'SIDI BERNOUSSI (AR)',
      'SIDI MOUMEN (AR)',
      'SIDI OTHMANE (AR)',
      'MECHOUAR DE CASABLANCA (M)',
    ),
    'CHEFCHAOUEN' => array(
      'CHEFCHAOUEN (M)',
      'AMTAR',
      'BAB BERRED',
      'BAB TAZA',
      'BNI AHMED CHERQIA',
      'BNI AHMED GHARBIA',
      'BNI BOUZRA',
      'BNI DARKOUL',
      'BNI FAGHLOUM',
      'BNI MANSOUR',
      'BNI RZINE',
      'BNI SALAH',
      'BNI SELMANE',
      'BNI SMIH',
      'DERDARA',
      'FIFI',
      'IOUNANE',
      'LAGHDIR',
      'MANSOURA',
      "M'TIOUA",
      'OUAOUZGANE',
      'OUED MALHA',
      'STEHA',
      'TALAMBOTE',
      'TAMOROT',
      'TANAQOUB',
      'TASSIFT',
      'TIZGANE',
    ),
    'CHICHAOUA' => array(
      'CHICHAOUA (M)',
      'IMINTANOUTE (M)',
      'ADASSIL',
      'AFALLA ISSEN',
      'AHDIL',
      'AIN TAZITOUNTE',
      'AIT HADDOU YOUSSEF',
      'AIT HADI',
      'ASSIF EL MAL',
      'BOUABOUT',
      'BOUABOUT AMDLANE',
      'DOUIRANE',
      'GMASSA',
      'ICHAMRAREN',
      'IMINDOUNIT',
      'IROHALEN',
      'KOUZEMT',
      'LALLA AAZIZA',
      'LAMZOUDIA',
      'MAJJAT',
      "M'ZOUDA",
      'NFIFA',
      "OUED L'BOUR",
      'OULAD MOUMNA',
      'RAHHALA',
      'SAIDATE',
      "SID L'MOKHTAR",
      'SIDI ABDELMOUMEN',
      'SIDI BOUZID ARRAGRAGUI',
      'SIDI GHANEM',
      "SIDI M'HAMED DALIL",
      'TAOULOUKOULT',
      'TIMEZGADIOUINE',
      'TIMLILT',
      'ZAOUIA ANNAHLIA',
    ),
    'CHTOUKA AIT BAHA' => array(
      'AIT BAHA (M)',
      'BIOUGRA (M)',
      'AIT AMIRA',
      'AIT MILK',
      'AIT MZAL',
      'AIT OUADRIM',
      'AOUGUENZ',
      'BELFAA',
      'HILALA',
      'IDA OUGNIDIF',
      'IMI MQOURN',
      'INCHADEN',
      'MASSA',
      'OUAD ESSAFA',
      'SIDI ABDALLAH EL BOUCHOUARI',
      'SIDI BIBI',
      'SIDI BOUSHAB',
      'SIDI OUASSAY',
      'TANALT',
      'TARGUA NTOUCHKA',
      'TASSEGDELT',
      'TIZI NTAKOUCHT',
    ),
    'DARYOUCH' => array(
      'AIN ZOHRA',
      'AIT MAIT',
      'AMEJJAOU',
      'AZLAF',
      'BEN TAIEB',
      'BNI MARGHNINE',
      'BOUDINAR',
      'DAR EL KEBDANI',
      'IFERNI',
      'IJERMAOUAS',
      "M'HAJER",
      'MIDAR',
      'OUARDANA',
      'OULAD AMGHAR',
      'OULAD BOUBKER',
      'TAFERSIT',
      'TALILIT',
      'TAZAGHINE',
      'TEMSAMANE',
      'TROUGOUT',
      'TSAFT',
    ),
    'EL HAJEB' => array(
      'AGOURAI',
      'AIN TAOUJDATE',
      'AIT BOUIDMANE',
      'AIT BOURZOUINE',
      'AIT HARZ ALLAH',
      'AIT NAAMANE',
      'AIT OUIKHALFEN',
      'AIT YAAZEM',
      'BITIT',
      'EL-HAJEB',
      'IQADDAR',
      'JAHJOUH',
      'LAQSIR',
      'RAS IJERRI',
      'SABAA AIYOUN',
      'TAMCHACHATE',
    ),
    'EL JADIDA' => array(
      'AZEMMOUR (M)',
      'EL-JADIDA (M)',
      'LBIR JDID (M)',
      'BOULAOUANE',
      'CHAIBATE',
      'CHTOUKA',
      'HAOUZIA',
      'LAGHDIRA',
      'LAMHARZA ESSAHEL',
      'METTOUH',
      'MOGRESS',
      'MOULAY ABDALLAH',
      'OULAD AISSA',
      'OULAD HAMDANE',
      'OULAD RAHMOUNE',
      'OULAD SIDI ALI BEN YOUSSEF',
      'OULAD FREJ',
      'OULAD GHANEM',
      'OULAD HCINE',
      'SEBT SAISS',
      'SI HSAIEN BEN ABDERRAHMANE',
      'SIDI ABED',
      'SIDI ALI BEN HAMDOUCHE',
      "SIDI M'HAMED AKHDIM",
      'SIDI SMAIL',
      'ZAOUIAT LAKOUACEM',
      'ZAOUIAT SAISS',
    ),
    'EL KELAA DES SRAGHNA' => array(
      'EL KELAâ DES SRAGHNA(M)',
      'LAATTAOUIA (M)',
      'SIDI RAHHAL (M)',
      'TAMALLALT (M)',
      'ASSAHRIJ',
      'BOUYA OMAR',
      'CHOARA',
      'CHTAIBA',
      'DZOUZ',
      'EDDACHRA',
      'EL AAMRIA',
      'EL MARBOUH',
      'ERRAFIAYA',
      'FRAITA',
      'HIADNA',
      'JBIEL',
      'JOUALA',
      'LAATAMNA',
      'LAATTAOUIA ECH-CHAYBIA',
      'LOUED LAKHDAR',
      'LOUNASDA',
      'MAYATE',
      "M'ZEM SANHAJA",
      'OUARGUI',
      'OULAD AAMER',
      'OULAD AARRAD',
      'OULAD BOUALI LOUED',
      'OULAD CHERKI',
      'OULAD GHANEM',
      'OULAD KHALLOUF',
      'OULAD MASSAOUD',
      'OULAD MSABBEL',
      'OULAD SBIH',
      'OULAD YAACOUB',
      'OULAD ZARRAD',
      'SIDI AISSA BEN SLIMANE',
      'SIDI EL HATTAB',
      'SIDI MOUSSA',
      'SOUR EL AAZ',
      'TAOUZINT',
      'ZEMRANE',
      'ZEMRANE CHARQIA',
      'ZNADA',
    ),
    'ERRACHIDIA' => array(
      'AARAB SEBBAH GHERIS ',
      'AARAB SEBBAH ZIZ',
      "AGHBALOU N'KERDOUS",
      'AMELLAGOU',
      'AOUFOUS',
      'ARFOUD',
      "BNI M'HAMED-SIJELMASSA",
      'BOUDNIB',
      "CHORFA M'DAGHRA",
      'ER-RISSANI',
      'ER-RTEB',
      'ERRACHIDIA',
      'ES-SFALAT',
      'ES-SIFA',
      'ET-TAOUS',
      'FERKLA EL OULIA',
      'FERKLA-ES-SOUFLA',
      'FEZNA',
      'GHERIS EL OULOUI',
      'GHERIS ES-SOUFLI',
      'GOULMIMA',
      'JORF',
      'LKHENG',
      'MELAAB',
      'MOULAY ALI CHERIF',
      'OUED NAAM',
      'SIDI ALI',
      'TADIGHOUST',
      'TINEJDAD',
    ),
    'ESSEMARA' => array(
      'ES-SEMARA (M)',
      'AMGALA',
      'HAOUZA',
      'JDIRIYA',
      'SIDI AHMED LAAROUSSI',
      'TIFARITI',
    ),
    'ESSAOUIRA' => array(
      'AIT DAOUD (M)',
      'EL HANCHANE (M)',
      'ESSAOUIRA (M)',
      'TALMEST (M)',
      'TAMANAR (M)',
      'ADAGHAS',
      'AGLIF',
      'AGUERD',
      'AIT AISSI IHAHANE',
      'AIT SAID',
      'AQUERMOUD',
      'ASSAIS',
      'BIZDAD',
      'BOUZEMMOUR',
      'EZZAOUITE',
      'HAD DRA',
      'IDA OU AAZZA',
      'IDA OU GUELLOUL',
      'IDA OU KAZZOU',
      'IMGRADE',
      "IMI N'TLIT",
      'KECHOULA',
      'KORIMATE',
      'LAGDADRA',
      'LAHSINATE',
      'MEJJI',
      'MESKALA',
      "M'KHALIF",
      'MOUARID',
      'MOULAY BOUZARQTOUNE',
      "M'RAMER",
      'MZILATE',
      "OULAD M'RABET",
      'OUNAGHA',
      'SIDI ABDELJALIL',
      'SIDI AHMED ESSAYEH',
      'SIDI AISSA REGRAGUI',
      'SIDI ALI EL KORATI',
      'SIDI BOULAALAM',
      'SIDI EL JAZOULI',
      'SIDI GHANEME',
      'SIDI HMAD OU HAMED',
      "SIDI H'MAD OU M'BAREK",
      'SIDI ISHAQ',
      'SIDI KAOUKI',
      'SIDI LAAROUSSI',
      "SIDI M'HAMED OU MARZOUQ",
      'SMIMOU',
      'TAFEDNA',
      'TAFETACHTE',
      'TAHELOUANTE',
      'TAKATE',
      'TAKOUCHT',
      'TARGANTE',
      'TIDZI',
      'TIMZGUIDA OUFTAS',
      'ZAOUIAT BEN HMIDA',
    ),
    'FAHS ANJRA' => array(
      'AL BAHRAOYINE',
      'ANJRA',
      'JOUAMAA',
      'KSAR EL MAJAZ',
      'KSAR SGHIR',
      'LAAOUAMA',
      'MALLOUSSA',
      'TAGHRAMT',
    ),
    'FES' => array(
      'FES',
      'AGDAL (AR)',
      'FES-MEDINA (AR)',
      'JNAN EL OUARD (AR)',
      'EL MARINIYINE (AR)',
      'SAISS (AR)',
      'ZOUAGHA (AR)',
      'MECHOUAR FES JDID (M)',
      'AIN BIDA',
      'OULAD TAYEB',
      'SIDI HARAZEM',
    ),
    'FIGUIG' => array(
      'BOUARFA (M)',
      'FIGUIG (M)',
      'ABBOU LAKHAL',
      'AIN CHOUATER',
      'BNI GUIL',
      'BNI TADJITE',
      'BOUANANE',
      'BOUCHAOUENE',
      'BOUMERIEME',
      'MAATARKA',
      'TALSINT',
      'TENDRARA',
      'AIN CHIR',
    ),
    'FQUIH BEN SALEH' => array(
      'FQUIH BEN SALAH (M)',
      'OULAD AYAD (M)',
      'SOUK SEBT OULAD NEMMA (M)',
      'BNI CHEGDALE',
      'BNI OUKIL',
      'BRADIA',
      'DAR OULD ZIDOUH',
      'HAD BOUMOUSSA',
      'HEL MERBAA',
      'AL KHALFIA',
      'KRIFATE',
      'OULAD BOURAHMOUNE',
      'OULAD NACER',
      'OULAD ZMAM',
      'SIDI AISSA BEN ALI',
      'SIDI HAMMADI',
    ),
    'GUELMIM' => array(
      'BOUIZAKARNE (M)',
      'GUELMIM (M)',
      'ABAYNOU',
      'ADAY',
      'AFERKAT',
      'AIT BOUFOULEN',
      'AMTDI',
      'ASRIR',
      'ECHATEA EL ABIED',
      'FASK',
      'IFRANE ATLAS SAGHIR',
      'LABYAR',
      'LAQSABI TAGOUST',
      'RASS OUMLIL',
      'TAGANTE',
      'TAGHJIJT',
      'TALIOUINE ASSAKA (M)',
      'TARGA WASSAY',
      'TIGLIT',
      'TIMOULAY',
    ),
    'GUERSIF' => array(
      'GUERCIF (M)',
      'ASSEBBAB',
      'BARKINE',
      'HOUARA OULAD RAHO',
      'LAMRIJA',
      'MAZGUITAM',
      'OULAD BOURIMA',
      'RAS LAKSAR',
      'SAKA',
      'TADDART',
    ),
    'IFRANE' => array(
      'AIN-LEUH',
      'AZROU',
      'BEN SMIM',
      'DAYATE-AOUA',
      'IFRANE',
      'OUED IFRANE',
      'SIDI ELMAKHFI',
      'TIGRIGRA',
      'TIMAHDITE',
      'TIZGUITE',
    ),
    'INEZGANE AIT MELLOUL' => array(
      'AIT MELLOUL (M)',
      'DCHEIRA EL JIHADIA (M)',
      'INEZGANE (M)',
      'LQLIAA',
      'OULAD DAHOU',
      'TEMSIA',
    ),
    'JERADA' => array(
      'AIN BNI MATHAR (M)',
      'JERADA (M)',
      'TOUISSIT (M)',
      'BNI MATHAR',
      'GAFAIT',
      'GUENFOUDA',
      'LAAOUINATE',
      'LEBKHATA',
      'MRIJA',
      'OULAD GHZIYEL',
      'OULAD SIDI ABDELHAKEM',
      'RAS ASFOUR',
      'SIDI BOUBKER',
      'TIOULI',
    ),
    'KENITRA' => array(
      'KENITRA (M)',
      'MEHDYA (M)',
      'SOUK EL ARBAA (M)',
      'AMEUR SEFLIA',
      'ARBAOUA',
      'BAHHARA OULAD AYAD',
      'BENI MALEK',
      'BEN MANSOUR',
      'CHOUAFAA',
      'HADDADA',
      'KARIAT BEN AOUDA',
      'LALLA MIMOUNA',
      'MNASRA',
      'MOGRANE',
      'MOULAY BOUSSELHAM',
      'OUED EL MAKHAZINE',
      'OULAD SLAMA',
      'SIDI ALLAL TAZI',
      'SIDI BOUBKER EL HAJ',
      'SIDI MOHAMED LAHMAR',
      'SIDI TAIBI',
      'SOUK TLET EL GHARB',
      'SIDI MOHAMED BEN MANSOUR',
    ),
    'KHEMISSET' => array(
      'KHEMISSET (M)',
      'ROMMANI (M)',
      'TIFLET (M)',
      'AIN JOHRA-SIDI BOUKHALKHAL',
      'AIN SBIT',
      'AIT BELKACEM',
      'AIT BOUYAHYA EL HAJJAMA',
      'AIT ICHOU',
      'AIT IKKOU',
      'AIT MALEK',
      'AIT MIMOUNE',
      'AIT OURIBEL',
      'AIT SIBERNE',
      'AIT YADINE',
      'BOUQACHMIR',
      'BRACHOUA',
      'EL GANZRA',
      'EZZHILIGA',
      'HOUDERRANE',
      'JEMAAT MOUL BLAD',
      'KHEMIS SIDI YAHYA',
      'LAGHOUALEM',
      'MAAZIZ',
      'MAJMAA TOLBA',
      'MARCHOUCH',
      "M'QAM TOLBA",
      'MOULAY DRISS AGHBAL',
      'OULMES',
      'SFASSIF',
      'SIDI ABDERRAZAK',
      'SIDI ALLAL EL BAHRAOUI',
      'SIDI ALLAL LAMSADDER',
      'AIT ALI OULAHCEN',
      'SIDI EL GHANDOUR',
      'TIDDAS',
      'AIT OURBIL',
    ),
    'KHENIFRA' => array(
      'AGUELMAM AZEGZA',
      'AGUELMOUS',
      'AIT ISHAQ',
      'AIT SAADELLI',
      'EL BORJ',
      'EL HAMMAM',
      'EL KBAB',
      'HAD BOUHSSOUSSEN',
      'KERROUCHEN',
      'KHENIFRA',
      'LEHRI',
      "M'RIRT",
      'MOHA OU HAMMOU-ZAYANI',
      'MOULAY BOUAZZA',
      'OUAOUMANA',
      'OUM RABIA',
      'SEBT AIT RAHOU',
      'SIDI AMAR',
      'SIDI HCINE',
      'SID LAMINE',
      'SIDI YAHYA OU SAAD',
      'TIGHASSALINE',
    ),
    'KHOURIBGA' => array(
      'BEJAAD (M)',
      'BOUJNIBA (M)',
      'HATTANE (M)',
      'KHOURIBGA (M)',
      'OUED ZEM (M)',
      'AIN KAICHER',
      'AIT AMMAR',
      'BIR MEZOUI',
      'BNI BATAOU',
      'BNI SMIR',
      'BNI YKHLEF',
      'BNI ZRANTEL',
      'BOUKHRISSE',
      'BOULANOUARE',
      'BRAKSA',
      'CHOUGRANE',
      'EL FOQRA',
      'KASBAT TROCH',
      'LAGFAF',
      'LAGNADIZ',
      'MAADNA',
      "M'FASSIS",
      'OULAD ABDOUNE',
      'OULAD AISSA',
      'OULAD AZZOUZ',
      'OULAD BOUGHADI',
      'OULAD FENNANE',
      'OULAD FTATA',
      'OULAD GOUAOUCH',
      'ROUACHED',
      'TACHRAFAT',
    ),
    'LAAYOUNE' => array(
      'EL MARSA (M)',
      'LAAYOUNE (M)',
      'BOUKRAA',
      'DCHEIRA',
      'FOUM EL OUED',
    ),
    'Rhode Island' => array(
      'Bristol',
      'Kent',
      'Newport',
      'Providence',
      'Washington',
    ),
    'South Carolina' => array(
      'Abbeville',
      'Aiken',
      'Allendale',
      'Anderson',
      'Bamberg',
      'Barnwell',
      'Beaufort',
      'Berkeley',
      'Calhoun',
      'Charleston',
      'Cherokee',
      'Chester',
      'Chesterfield',
      'Clarendon',
      'Colleton',
      'Darlington',
      'Dillon',
      'Dorchester',
      'Edgefield',
      'Fairfield',
      'Florence',
      'Georgetown',
      'Greenville',
      'Greenwood',
      'Hampton',
      'Horry',
      'Jasper',
      'Kershaw',
      'Lancaster',
      'Laurens',
      'Lee',
      'Lexington',
      'Marion',
      'Marlboro',
      'McCormick',
      'Newberry',
      'Oconee',
      'Orangeburg',
      'Pickens',
      'Richland',
      'Saluda',
      'Spartanburg',
      'Sumter',
      'Union',
      'Williamsburg',
      'York',
    ),
    'South Dakota' => array(
      'Aurora',
      'Beadle',
      'Bennett',
      'Bon Homme',
      'Brookings',
      'Brown',
      'Brule',
      'Buffalo',
      'Butte',
      'Campbell',
      'Charles Mix',
      'Clark',
      'Clay',
      'Codington',
      'Corson',
      'Custer',
      'Davison',
      'Day',
      'Deuel',
      'Dewey',
      'Douglas',
      'Edmunds',
      'Fall River',
      'Faulk',
      'Grant',
      'Gregory',
      'Haakon',
      'Hamlin',
      'Hand',
      'Hanson',
      'Harding',
      'Hughes',
      'Hutchinson',
      'Hyde',
      'Jackson',
      'Jerauld',
      'Jones',
      'Kingsbury',
      'Lake',
      'Lawrence',
      'Lincoln',
      'Lyman',
      'Marshall',
      'McCook',
      'McPherson',
      'Meade',
      'Mellette',
      'Miner',
      'Minnehaha',
      'Moody',
      'Pennington',
      'Perkins',
      'Potter',
      'Roberts',
      'Sanborn',
      'Shannon',
      'Spink',
      'Stanley',
      'Sully',
      'Todd',
      'Tripp',
      'Turner',
      'Union',
      'Walworth',
      'Yankton',
      'Ziebach',
    ),
    'Tennessee' => array(
      'Anderson',
      'Bedford',
      'Benton',
      'Bledsoe',
      'Blount',
      'Bradley',
      'Campbell',
      'Cannon',
      'Carroll',
      'Carter',
      'Cheatham',
      'Chester',
      'Claiborne',
      'Clay',
      'Cocke',
      'Coffee',
      'Crockett',
      'Cumberland',
      'Davidson',
      'Decatur',
      'DeKalb',
      'Dickson',
      'Dyer',
      'Fayette',
      'Fentress',
      'Franklin',
      'Gibson',
      'Giles',
      'Grainger',
      'Greene',
      'Grundy',
      'Hamblen',
      'Hamilton',
      'Hancock',
      'Hardeman',
      'Hardin',
      'Hawkins',
      'Haywood',
      'Henderson',
      'Henry',
      'Hickman',
      'Houston',
      'Humphreys',
      'Jackson',
      'Jefferson',
      'Johnson',
      'Knox',
      'Lake',
      'Lauderdale',
      'Lawrence',
      'Lewis',
      'Lincoln',
      'Loudon',
      'Macon',
      'Madison',
      'Marion',
      'Marshall',
      'Maury',
      'McMinn',
      'McNairy',
      'Meigs',
      'Monroe',
      'Montgomery',
      'Moore',
      'Morgan',
      'Obion',
      'Overton',
      'Perry',
      'Pickett',
      'Polk',
      'Putnam',
      'Rhea',
      'Roane',
      'Robertson',
      'Rutherford',
      'Scott',
      'Sequatchie',
      'Sevier',
      'Shelby',
      'Smith',
      'Stewart',
      'Sullivan',
      'Sumner',
      'Tipton',
      'Trousdale',
      'Unicoi',
      'Union',
      'Van Buren',
      'Warren',
      'Washington',
      'Wayne',
      'Weakley',
      'White',
      'Williamson',
      'Wilson',
    ),
    'Texas' => array(
      'Anderson',
      'Andrews',
      'Angelina',
      'Aransas',
      'Archer',
      'Armstrong',
      'Atascosa',
      'Austin',
      'Bailey',
      'Bandera',
      'Bastrop',
      'Baylor',
      'Bee',
      'Bell',
      'Bexar',
      'Blanco',
      'Borden',
      'Bosque',
      'Bowie',
      'Brazoria',
      'Brazos',
      'Brewster',
      'Briscoe',
      'Brooks',
      'Brown',
      'Burleson',
      'Burnet',
      'Caldwell',
      'Calhoun',
      'Callahan',
      'Cameron',
      'Camp',
      'Carson',
      'Cass',
      'Castro',
      'Chambers',
      'Cherokee',
      'Childress',
      'Clay',
      'Cochran',
      'Coke',
      'Coleman',
      'Collin',
      'Collingsworth',
      'Colorado',
      'Comal',
      'Comanche',
      'Concho',
      'Cooke',
      'Coryell',
      'Cottle',
      'Crane',
      'Crockett',
      'Crosby',
      'Culberson',
      'Dallam',
      'Dallas',
      'Dawson',
      'De Witt',
      'Deaf Smith',
      'Delta',
      'Denton',
      'Dickens',
      'Dimmit',
      'Donley',
      'Duval',
      'Eastland',
      'Ector',
      'Edwards',
      'El Paso',
      'Ellis',
      'Erath',
      'Falls',
      'Fannin',
      'Fayette',
      'Fisher',
      'Floyd',
      'Foard',
      'Fort Bend',
      'Franklin',
      'Freestone',
      'Frio',
      'Gaines',
      'Galveston',
      'Garza',
      'Gillespie',
      'Glasscock',
      'Goliad',
      'Gonzales',
      'Gray',
      'Grayson',
      'Gregg',
      'Grimes',
      'Guadalupe',
      'Hale',
      'Hall',
      'Hamilton',
      'Hansford',
      'Hardeman',
      'Hardin',
      'Harris',
      'Harrison',
      'Hartley',
      'Haskell',
      'Hays',
      'Hemphill',
      'Henderson',
      'Hidalgo',
      'Hill',
      'Hockley',
      'Hood',
      'Hopkins',
      'Houston',
      'Howard',
      'Hudspeth',
      'Hunt',
      'Hutchinson',
      'Irion',
      'Jack',
      'Jackson',
      'Jasper',
      'Jeff Davis',
      'Jefferson',
      'Jim Hogg',
      'Jim Wells',
      'Johnson',
      'Jones',
      'Karnes',
      'Kaufman',
      'Kendall',
      'Kenedy',
      'Kent',
      'Kerr',
      'Kimble',
      'King',
      'Kinney',
      'Kleberg',
      'Knox',
      'La Salle',
      'Lamar',
      'Lamb',
      'Lampasas',
      'Lavaca',
      'Lee',
      'Leon',
      'Liberty',
      'Limestone',
      'Lipscomb',
      'Live Oak',
      'Llano',
      'Loving',
      'Lubbock',
      'Lynn',
      'Madison',
      'Marion',
      'Martin',
      'Mason',
      'Matagorda',
      'Maverick',
      'McCulloch',
      'McLennan',
      'McMullen',
      'Medina',
      'Menard',
      'Midland',
      'Milam',
      'Mills',
      'Mitchell',
      'Montague',
      'Montgomery',
      'Moore',
      'Morris',
      'Motley',
      'Nacogdoches',
      'Navarro',
      'Newton',
      'Nolan',
      'Nueces',
      'Ochiltree',
      'Oldham',
      'Orange',
      'Palo Pinto',
      'Panola',
      'Parker',
      'Parmer',
      'Pecos',
      'Polk',
      'Potter',
      'Presidio',
      'Rains',
      'Randall',
      'Reagan',
      'Real',
      'Red River',
      'Reeves',
      'Refugio',
      'Roberts',
      'Robertson',
      'Rockwall',
      'Runnels',
      'Rusk',
      'Sabine',
      'San Augustine',
      'San Jacinto',
      'San Patricio',
      'San Saba',
      'Schleicher',
      'Scurry',
      'Shackelford',
      'Shelby',
      'Sherman',
      'Smith',
      'Somervell',
      'Starr',
      'Stephens',
      'Sterling',
      'Stonewall',
      'Sutton',
      'Swisher',
      'Tarrant',
      'Taylor',
      'Terrell',
      'Terry',
      'Throckmorton',
      'Titus',
      'Tom Green',
      'Travis',
      'Trinity',
      'Tyler',
      'Upshur',
      'Upton',
      'Uvalde',
      'Val Verde',
      'Van Zandt',
      'Victoria',
      'Walker',
      'Waller',
      'Ward',
      'Washington',
      'Webb',
      'Wharton',
      'Wheeler',
      'Wichita',
      'Wilbarger',
      'Willacy',
      'Williamson',
      'Wilson',
      'Winkler',
      'Wise',
      'Wood',
      'Yoakum',
      'Young',
      'Zapata',
      'Zavala',
    ),
    'Utah' => array(
      'Beaver',
      'Box Elder',
      'Cache',
      'Carbon',
      'Daggett',
      'Davis',
      'Duchesne',
      'Emery',
      'Garfield',
      'Grand',
      'Iron',
      'Juab',
      'Kane',
      'Millard',
      'Morgan',
      'Piute',
      'Rich',
      'Salt Lake',
      'San Juan',
      'Sanpete',
      'Sevier',
      'Summit',
      'Tooele',
      'Uintah',
      'Utah',
      'Wasatch',
      'Washington',
      'Wayne',
      'Weber',
    ),
    'Vermont' => array(
      'Addison',
      'Bennington',
      'Caledonia',
      'Chittenden',
      'Essex',
      'Franklin',
      'Grand Isle',
      'Lamoille',
      'Orange',
      'Orleans',
      'Rutland',
      'Washington',
      'Windham',
      'Windsor',
    ),
    'Virginia' => array(
      'Accomack',
      'Albemarle',
      'Alleghany',
      'Amelia',
      'Amherst',
      'Appomattox',
      'Arlington',
      'Augusta',
      'Bath',
      'Bedford',
      'Bland',
      'Botetourt',
      'Brunswick',
      'Buchanan',
      'Buckingham',
      'Campbell',
      'Caroline',
      'Carroll',
      'Charles City',
      'Charlotte',
      'Chesterfield',
      'City of Alexandria',
      'City of Bedford',
      'City of Bristol',
      'City of Buena Vista',
      'City of Charlottesville',
      'City of Chesapeake',
      'City of Clifton Forge',
      'City of Colonial Heights',
      'City of Covington',
      'City of Danville',
      'City of Emporia',
      'City of Fairfax',
      'City of Falls Church',
      'City of Franklin',
      'City of Fredericksburg',
      'City of Galax',
      'City of Hampton',
      'City of Harrisonburg',
      'City of Hopewell',
      'City of Lexington',
      'City of Lynchburg',
      'City of Manassas',
      'City of Manassas Park',
      'City of Martinsville',
      'City of Newport News',
      'City of Norfolk',
      'City of Norton',
      'City of Petersburg',
      'City of Poquoson',
      'City of Portsmouth',
      'City of Radford',
      'City of Richmond',
      'City of Roanoke',
      'City of Salem',
      'City of South Boston',
      'City of Staunton',
      'City of Suffolk',
      'City of Virginia Beach',
      'City of Waynesboro',
      'City of Williamsburg',
      'City of Winchester',
      'Clarke',
      'Craig',
      'Culpeper',
      'Cumberland',
      'Dickenson',
      'Dinwiddie',
      'Essex',
      'Fairfax',
      'Fauquier',
      'Floyd',
      'Fluvanna',
      'Franklin',
      'Frederick',
      'Giles',
      'Gloucester',
      'Goochland',
      'Grayson',
      'Greene',
      'Greensville',
      'Halifax',
      'Hanover',
      'Henrico',
      'Henry',
      'Highland',
      'Isle of Wight',
      'James City',
      'King and Queen',
      'King George',
      'King William',
      'Lancaster',
      'Lee',
      'Loudoun',
      'Louisa',
      'Lunenburg',
      'Madison',
      'Mathews',
      'Mecklenburg',
      'Middlesex',
      'Montgomery',
      'Nelson',
      'New Kent',
      'Northampton',
      'Northumberland',
      'Nottoway',
      'Orange',
      'Page',
      'Patrick',
      'Pittsylvania',
      'Powhatan',
      'Prince Edward',
      'Prince George',
      'Prince William',
      'Pulaski',
      'Rappahannock',
      'Richmond',
      'Roanoke',
      'Rockbridge',
      'Rockingham',
      'Russell',
      'Scott',
      'Shenandoah',
      'Smyth',
      'Southampton',
      'Spotsylvania',
      'Stafford',
      'Surry',
      'Sussex',
      'Tazewell',
      'Warren',
      'Washington',
      'Westmoreland',
      'Wise',
      'Wythe',
      'York',
    ),
    'Washington' => array(
      'Adams',
      'Asotin',
      'Benton',
      'Chelan',
      'Clallam',
      'Clark',
      'Columbia',
      'Cowlitz',
      'Douglas',
      'Ferry',
      'Franklin',
      'Garfield',
      'Grant',
      'Grays Harbor',
      'Island',
      'Jefferson',
      'King',
      'Kitsap',
      'Kittitas',
      'Klickitat',
      'Lewis',
      'Lincoln',
      'Mason',
      'Okanogan',
      'Pacific',
      'Pend Oreille',
      'Pierce',
      'San Juan',
      'Skagit',
      'Skamania',
      'Snohomish',
      'Spokane',
      'Stevens',
      'Thurston',
      'Wahkiakum',
      'Walla Walla',
      'Whatcom',
      'Whitman',
      'Yakima',
    ),
    'West Virginia' => array(
      'Barbour',
      'Berkeley',
      'Boone',
      'Braxton',
      'Brooke',
      'Cabell',
      'Calhoun',
      'Clay',
      'Doddridge',
      'Fayette',
      'Gilmer',
      'Grant',
      'Greenbrier',
      'Hampshire',
      'Hancock',
      'Hardy',
      'Harrison',
      'Jackson',
      'Jefferson',
      'Kanawha',
      'Lewis',
      'Lincoln',
      'Logan',
      'Marion',
      'Marshall',
      'Mason',
      'McDowell',
      'Mercer',
      'Mineral',
      'Mingo',
      'Monongalia',
      'Monroe',
      'Morgan',
      'Nicholas',
      'Ohio',
      'Pendleton',
      'Pleasants',
      'Pocahontas',
      'Preston',
      'Putnam',
      'Raleigh',
      'Randolph',
      'Ritchie',
      'Roane',
      'Summers',
      'Taylor',
      'Tucker',
      'Tyler',
      'Upshur',
      'Wayne',
      'Webster',
      'Wetzel',
      'Wirt',
      'Wood',
      'Wyoming',
    ),
    'Wisconsin' => array(
      'Adams',
      'Ashland',
      'Barron',
      'Bayfield',
      'Brown',
      'Buffalo',
      'Burnett',
      'Calumet',
      'Chippewa',
      'Clark',
      'Columbia',
      'Crawford',
      'Dane',
      'Dodge',
      'Door',
      'Douglas',
      'Dunn',
      'Eau Claire',
      'Florence',
      'Fond du Lac',
      'Forest',
      'Grant',
      'Green',
      'Green Lake',
      'Iowa',
      'Iron',
      'Jackson',
      'Jefferson',
      'Juneau',
      'Kenosha',
      'Kewaunee',
      'La Crosse',
      'Lafayette',
      'Langlade',
      'Lincoln',
      'Manitowoc',
      'Marathon',
      'Marinette',
      'Marquette',
      'Menominee',
      'Milwaukee',
      'Monroe',
      'Oconto',
      'Oneida',
      'Outagamie',
      'Ozaukee',
      'Pepin',
      'Pierce',
      'Polk',
      'Portage',
      'Price',
      'Racine',
      'Richland',
      'Rock',
      'Rusk',
      'Sauk',
      'Sawyer',
      'Shawano',
      'Sheboygan',
      'St. Croix',
      'Taylor',
      'Trempealeau',
      'Vernon',
      'Vilas',
      'Walworth',
      'Washburn',
      'Washington',
      'Waukesha',
      'Waupaca',
      'Waushara',
      'Winnebago',
      'Wood',
    ),
    'Wyoming' => array(
      'Albany',
      'Big Horn',
      'Campbell',
      'Carbon',
      'Converse',
      'Crook',
      'Fremont',
      'Goshen',
      'Hot Springs',
      'Johnson',
      'Laramie',
      'Lincoln',
      'Natrona',
      'Niobrara',
      'Park',
      'Platte',
      'Sheridan',
      'Sublette',
      'Sweetwater',
      'Teton',
      'Uinta',
      'Washakie',
      'Weston',
    ),
  );

  return array($countryIso => $counties);
}

/**
 * Check and load counties
 */

function moroccocommunes_loadcounties() {

  $allCounties = moroccocommunes_listcounties();

  foreach ($allCounties as $countryIso => $counties) {
    static $dao = NULL;
    if (!$dao) {
      $dao = new CRM_Core_DAO();
    }

    // Get array of states.
    try {
      $result = civicrm_api3('Country', 'getsingle', array(
        'iso_code' => $countryIso,
        'api.Address.getoptions' => array(
          'field' => 'state_province_id',
          'country_id' => '$value.id',
          'sequential' => 0,
        ),
      ));
    }
    catch (CiviCRM_API3_Exception $e) {
      $error = $e->getMessage();
      CRM_Core_Error::debug_log_message(ts('API Error: %1', array(
        'domain' => 'org.ndi.moroccocommunes',
        1 => $error,
      )));
      return FALSE;
    }

    if (empty($result['api.Address.getoptions']['values'])) {
      return FALSE;
    }
    $states = $result['api.Address.getoptions']['values'];

    // go state-by-state to check existing counties

    foreach ($counties as $stateName => $state) {
      $id = array_search($stateName, $states);
      if ($id === FALSE) {
        continue;
      }

      $check = "SELECT name FROM civicrm_county WHERE state_province_id = $id";
      $results = CRM_Core_DAO::executeQuery($check);
      $existing = array();
      while ($results->fetch()) {
        $existing[] = $results->name;
      }

      // identify counties needing to be loaded
      $add = array_diff($state, $existing);

      $insert = array();
      foreach ($add as $county) {
        $countye = $dao->escape($county);
        $insert[] = "('$countye', $id)";
      }

      // put it into queries of 50 counties each
      for($i = 0; $i < count($insert); $i = $i+50) {
        $inserts = array_slice($insert, $i, 50);
        $query = "INSERT INTO civicrm_county (name, state_province_id) VALUES ";
        $query .= implode(', ', $inserts);
        CRM_Core_DAO::executeQuery($query);
      }
    }
  }

  return TRUE;
}

/**
 * Implementation of hook_civicrm_install
 *
 * @link http://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_install
 */
function moroccocommunes_civicrm_install() {
  moroccocommunes_loadcounties();
}

/**
 * Implementation of hook_civicrm_enable
 *
 * @link http://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_enable
 */
function moroccocommunes_civicrm_enable() {
  moroccocommunes_loadcounties();
}

/**
 * Implementation of hook_civicrm_upgrade
 *
 * @param $op string, the type of operation being performed; 'check' or 'enqueue'
 * @param $queue CRM_Queue_Queue, (for 'enqueue') the modifiable list of pending up upgrade tasks
 *
 * @return mixed  based on op. for 'check', returns array(boolean) (TRUE if upgrades are pending)
 *                for 'enqueue', returns void
 *
 * @link http://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_upgrade
 */
function moroccocommunes_civicrm_upgrade($op, CRM_Queue_Queue $queue = NULL) {
  moroccocommunes_loadcounties();
}
